name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi There, Sorry to see that you have issues with VCP, we will do our best to fix your issues ASAP!"
        pr-message: "Hi There, Welcome to VCP world!!"
